### ISSUE TITLE
Add TypeScript support for AWS Lambda Powertools

### ISSUE THREAD

**Issue by saragerion** [awslabs/aws-lambda-powertools-roadmap#26]
**Runtime:** 
Node.js

**Is your feature request related to a problem? Please describe**
AWS Lambda supports multiple languages through the use of [runtimes](https://docs.aws.amazon.com/lambda/latest/dg/lambda-runtimes.html), one of them being Node.js. In the [Serverless Lens](https://docs.aws.amazon.com/wellarchitected/latest/serverless-applications-lens/welcome.html) for the Well Architected Framework, we suggest several best practices for observability such as structured logging, distributed tracing, and monitoring of metrics. The suite of utilities of the AWS Lambda Powertools help developers with the adoption of best practices.
Today, AWS Lambda Powertools is available for the Python and Java runtimes.

**Describe the solution you'd like**
AWS Lambda Powertools available for Node.js runtimes, written in **TypeScript**.

**Describe alternatives you've considered**
For the generation of metrics, traces and logs developers can use a number of different open-source libraries together, maintained by the AWS community, or implement that logic by themselves.

**If you provide guidance, is this something you'd like to contribute?**
Absolutely yes.

**Additional context**
The TypeScript Powertool will follow the same tenets as the other languages, and folks can expect the same core utilities/ functionalities being supported.

**Comment by santoshshinde2012** [comment]
@saragerion Thanks for opening the feature request. Earlier I was looking for the same but it is not available for node js with typescript. It will be good to have the TypeScript support for AWS Lambda Powertools.

**Comment by mihilmy** [comment]
I would love to contribute as well!

**Comment by saragerion** [comment]
I am ✨  thrilled ✨  to announce that the beta release of AWS Lambda Powertools TypeScript is now public!
https://github.com/awslabs/aws-lambda-powertools-typescript/releases

Quick links:
Documentation: https://awslabs.github.io/aws-lambda-powertools-typescript/latest/
Repository: https://github.com/awslabs/aws-lambda-powertools-typescript
Release notes: https://github.com/awslabs/aws-lambda-powertools-typescript/releases
