### ISSUE TITLE
Official support for MyPy

### ISSUE THREAD

**Issue by heitorlessa** [awslabs/aws-lambda-powertools-roadmap#3]
> Original author: @huonw

**Runtime e.g. Python, Java, all of them.** Python

**Is your feature request related to a problem? Please describe.**

As per in the original [Lambda Powertools Python Discussions](https://github.com/awslabs/aws-lambda-powertools-python/discussions/330), MyPy isn't officially supported and can fail when type checking Tracer, as an example.

**Describe the solution you'd like**

Lambda Powertools to consider MyPy customers and include MyPy in the pipeline to make it compliant :-)

**Describe alternatives you've considered**

Ignoring type errors

**Is this something you'd like to contribute if you had guidance?**

**Additional context**

**Comment by heitorlessa** [comment]
As of 1.18.1, we've made substantial progress on here and have only a handful of issues to fix. I'll mark this as shipped once we address all of them and include MyPy in the CI to keep it consistent

**Comment by huonw** [comment]
> Bug fixes were largely on MyPy errors (~600 to 38) across the entire code base

That's awesome. Thanks for the update!

**Comment by heitorlessa** [comment]
We've got 14 errors now down from 38. More improvements to come as we will make a release dedicated to it, and enable MyPy at CI by default once these are addressed to prevent regressions

**Comment by heitorlessa** [comment]
Just merged. @huonw thank you for your patience on this -- next release will have full Mypy support now!!

**Comment by huonw** [comment]
That's exciting! Thanks for the updates

**Comment by heitorlessa** [comment]
Closing as this is now official as of two releases ago ;)
