### ISSUE TITLE
Add Support for API Gateway Lambda authorizer

### ISSUE THREAD

**Issue by gwlester** [awslabs/aws-lambda-powertools-roadmap#33]
**Is your feature request related to a problem? Please describe.**

The API Gateway Resolver does not (appear) to support the ability to dispatch to a function as a Lambda authorizer.

**Describe the solution you'd like**

Add support to be able to dispatch to a function that is a Lambda authorizer.

**Describe alternatives you've considered**

**Additional context**

**Comment by michaelbrewer** [comment]
@gwlester  - this is getting a little closer to being done. The next PR is focusing on the HTTP api lambda authorizer and then finally Rest api lambda authorizer will be done.

- https://github.com/awslabs/aws-lambda-powertools-python/pull/620

**Comment by heitorlessa** [comment]
Now avaiable in 1.20.0 both for v1 and v2: https://awslabs.github.io/aws-lambda-powertools-python/latest/utilities/data_classes/#api-gateway-authorizer
