### ISSUE TITLE
Allow APIGatewayResolver to handle Custom Domain with Mapping and still work

### ISSUE THREAD

**Issue by walmsles** [awslabs/aws-lambda-powertools-roadmap#34]
**Is your feature request related to a problem? Please describe.**
Have opened as a feature request as I believe this is not exactly a bug, perhaps an oversight in the ApiGatewayResolver design (happy to discuss more).  
A couple of months ago I developed an API for a project whose API gateway was associated with a custom domain. 
This week I built a new API extension (new gateway) using AWS Lambda Powertools for Python and have applied several routes into the one lambda using the API Gateway Resolver with the intention of adding to the same custom domain since want the ApiGateway to be hosted on the one common DNS domain.  When associating a second gateway to a custom domain you must associate a  mapping for the additional gateways so the API paths do not collide and everything works.

Within my lambda resolver setup for this second gateway if I have a resolver route of "/status" setup this works fine if it is mounted as-is on the root of the domain.  If I add to a custom domain as a second gateway I need to add in a "mapping", for example, sake let's say I choose "unique".  The AWS API Gateway event "path" for the API when I call it as "https://mycustomdomain.com/unique/status" is set to "/unique/status" which means the power tools Resolver will respond with a "404, NOT FOUND" since that path is not setup within the Resolver routes.

I have noticed that the "resource" path in the event correctly holds the route as "/status" but the path holds the route as "/unique/status"

This is a complicated one - the ApiGatewayResolver does not allow me to mount the gateways developed with this component on any custom domain with a mapping and have the lambda API actually work - I actually kind of think this is a bug but not raising as such since the implementation seems perfectly reasonable.

**Describe the solution you'd like**
What I would ideally like is the freedom to be able to mount my Python API to a custom domain using any mapping I choose and still have the API resolver find my routes within the lambda code correctly.

The current implementation uses the "path" of the ApiGateway Lambda event which houses the complete API path including the mapping which breaks the resolver.

**Describe alternatives you've considered**
As a work around I can simply change my routes to include the proposed mapping but then this stops me from being able to use Api Gateway configuration to remap an API in the future and actually have it work without changing my code which is not ideal given this is a feature of using Services like the AWS Api gateway.

**Additional context**
This kind of also brings into question how the Event content is generated and passed to lambda by the ApiGateway since one could argue it makes no sense that the "path" also includes the logical "mapping" from the API gateway Custom Domain configuration (not an argument I want to start but a consideration given the logical config nature of this scenario).

I have taken a look at the event structure from this configuration and notice the "resource" contains a correct path that matches the route I have in my Lambda Resolver routes in python code but is possibly not ideal.

**Comment by heitorlessa** [comment]
/polls "Treat as a bugfix" "Treat as a breaking chance"

Putting it to a vote to make things easier.

**Comment by heitorlessa** [comment]
/polls "Treat as a bugfix" "Treat as a breaking change"

**Comment by heitorlessa** [comment]
This got even more complex as API GW support an arbitrary level of mapping paths and customers could have multiple of these. Added sample there: https://github.com/awslabs/aws-lambda-powertools-python/pull/579#issuecomment-900307854

**Comment by heitorlessa** [comment]
Now available in 1.20.0 and we support all discrepancies found in REST API, HTTP API v1 and v2 payloads

https://awslabs.github.io/aws-lambda-powertools-python/latest/core/event_handler/api_gateway/#custom-domain-api-mappings
