### ISSUE TITLE
Extend AppSyncResolver functionality to support splitting resolvers into multiple files

### ISSUE THREAD

**Issue by rakcy** [awslabs/aws-lambda-powertools-roadmap#43]
**Is your feature request related to a problem? Please describe.**
Similar to https://github.com/awslabs/aws-lambda-powertools-python/issues/644,  I was trying to find a way to split the resolvers into different files as our resolvers are too cluttered in one file currently.

**Describe the solution you'd like**
An appsync version like `app.register_blueprint(my_type_resolvers)` would be nice. Another possibility would be to have something like:
```
app.register_resolvers(type_name="MyType", resolver_class=MyType)
```

**Describe alternatives you've considered**
We've been adding all resolvers in the same file currently, which is becoming a bit cluttered.

**Comment by heitorlessa** [comment]
hey @rakcy this is now out as part of 1.22.0 release - available on PyPi, SAR, and soon Lambda Layer (version 4).

https://github.com/awslabs/aws-lambda-powertools-python/releases/tag/v1.22.0
