### ISSUE TITLE
DynamoDBPersistenceLayer should support Tables with Range Keys

### ISSUE THREAD

**Issue by Tankanow** [awslabs/aws-lambda-powertools-roadmap#45]
**Is your feature request related to a problem? Please describe.**

I cannot use the `DynamoDBPersistenceLayer` class when my table has HASH and RANGE keys. I do not want to create a separate table for tracking lambda idempotence. [channeling my inner Houlihan] One table to rule them all!

**Describe the solution you'd like**

I would like the `DynamoDBPersistenceLayer` to accept a configuration such that the HASH key is set to a known value, e.g. `idempotence#<feature-name>`, and the RANGE key contains the current values managed by the `data_record.idempotency_key`.

**Describe alternatives you've considered**

There are of course other HASH/RANGE key designs. Another possible design is to split the current `data_record.idempotency_key` value, which is `<function name>#<hash>`, to maybe be HASH key = `<function name>` and RANGE key = `<hash>`.

**Additional context**

I would like this to be a non-breaking change for current consumers. If we agree on the first HASH/RANGE key design proposal, the client could configure a `DynamoDBPersistenceLayer` with these extra parameters:
```
        key_attr_value: str = "idempotence",  # this is just a hardcoded value
        range_attr: str = "SK",               # this is the range key to store the current `data_record.idempotency_key`
```
If these are set, then `DynamoDBPersistenceLayer` uses the HASH/RANGE key implementation, else it reverts to HASH key implementation.

**Comment by heitorlessa** [comment]
hey @Tankanow this is now out as part of 1.22.0 release - available on PyPi, SAR, and soon Lambda Layer (version 4).

https://github.com/awslabs/aws-lambda-powertools-python/releases/tag/v1.22.0

HUGE THANK YOU for helping get this out!
