### ISSUE TITLE
Feature request: CodePipeline Lambda Event

### ISSUE THREAD

**Issue by jplock** [awslabs/aws-lambda-powertools-roadmap#5]
**Is your feature request related to a problem? Please describe.**

A CodePipeline data class for Lambda events with helper methods to use the embedded credentials to download an artifact from S3. 

https://docs.aws.amazon.com/codepipeline/latest/userguide/actions-invoke-lambda-function.html#actions-invoke-lambda-function-json-event-example

**Describe the solution you'd like**

see above

**Describe alternatives you've considered**

Manually accessing the event 

**Additional context**

**Comment by michaelbrewer** [comment]
@jplock this has been officially released now: [CodePipeline Job](https://awslabs.github.io/aws-lambda-powertools-python/latest/utilities/data_classes/#codepipeline-job)

**Comment by jplock** [comment]
Thank you for pushing this through @michaelbrewer !
