### ISSUE TITLE
feature(apigateway): define function to handle not found requests

### ISSUE THREAD

**Issue by rtcnerd** [awslabs/aws-lambda-powertools-roadmap#65]
Executing the following code does not trigger the rules. Ideally I would expect the rule="/not-found-error" to be triggered when an incorrect path is sent. The print statement is never printed. I get the default value. Am I missing something? 

from aws_lambda_powertools import Logger, Tracer
from aws_lambda_powertools.logging import correlation_paths
from aws_lambda_powertools.event_handler.api_gateway import ApiGatewayResolver
from aws_lambda_powertools.event_handler.exceptions import (
    BadRequestError,
    InternalServerError,
    NotFoundError,
    ServiceError,
    UnauthorizedError,
)

tracer = Tracer()
logger = Logger()

app = ApiGatewayResolver()

@app.get(rule="/bad-request-error")
def bad_request_error():
    # HTTP  400
    raise BadRequestError("Missing required parameter")

@app.get(rule="/unauthorized-error")
def unauthorized_error():
    # HTTP 401
    raise UnauthorizedError("Unauthorized")

@app.get(rule="/not-found-error")
def not_found_error():
    # HTTP 404
    print("Not found")
    raise NotFoundError

@app.get(rule="/internal-server-error")
def internal_server_error():
    # HTTP 500
    raise InternalServerError("Internal server error")

@app.get(rule="/service-error", cors=True)
def service_error():
    raise ServiceError(502, "Something went wrong!")
    # alternatively
    # from http import HTTPStatus
    # raise ServiceError(HTTPStatus.BAD_GATEWAY.value, "Something went wrong)

def handler(event, context):
    return app.resolve(event, context)

**Comment by heitorlessa** [comment]
hey @rtcnerd this is now available as part of today's 1.23.0 release :) Thank you again for this feature request!

**Comment by rtcnerd** [comment]
@heitorlessa many thanks for introducing the new feature. However when I try executing it on aws, i get the following error for not found:
[ERROR] TypeError: not_found() missing 1 required positional argument: 'func'
Traceback (most recent call last):
  File "/var/lang/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/var/task/lambda_function.py", line 19, in <module>
    @app.not_found()

**Comment by heitorlessa** [comment]
> @heitorlessa many thanks for introducing the new feature. However when I try executing your sample code on aws, i get the following error for not found:
> 
> [ERROR] TypeError: not_found() missing 1 required positional argument: 'func'
> 
> Traceback (most recent call last):
> 
>   File "/var/lang/lib/python3.9/importlib/__init__.py", line 127, in import_module
> 
>     return _bootstrap._gcd_import(name[level:], package, level)
> 
>   File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
> 
>   File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
> 
>   File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
> 
>   File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
> 
>   File "<frozen importlib._bootstrap_external>", line 850, in exec_module
> 
>   File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
> 
>   File "/var/task/lambda_function.py", line 19, in <module>
> 
>     @app.not_found()

🤦‍♂️ there's a syntax error in my comment up there - () - decorator should be @app.not_found not @app.not_found() or else you'll get the error you've got, my apologies.

The official docs are correct

https://awslabs.github.io/aws-lambda-powertools-python/latest/core/event_handler/api_gateway/#handling-not-found-routes

Let me know if you're still experiencing the same issue with the correct sample

**Comment by michaelbrewer** [comment]
@heitorlessa - should i accept `@app.not_found()` has well? just to safe?

**Comment by michaelbrewer** [comment]
@heitorlessa @rtcnerd - sorry about the errors with `()` I have added support for that too:

- https://github.com/awslabs/aws-lambda-powertools-python/pull/926

**Comment by michaelbrewer** [comment]
@rtcnerd - anything else missing from this?
