### ISSUE TITLE
Provide access to ApiGatewayResolver object from Router object

### ISSUE THREAD

**Issue by gwlester** [awslabs/aws-lambda-powertools-roadmap#68]
**Is your feature request related to a problem? Please describe.**

When attempting to use the, introduced in 1.22.0, Split routes with Router methods, we found that many of our end point functions needed access to the ApiGatewayResolver object.  This is due to the fact that we have subclassed the ApiGatewayResolver to add some application-specific functionality.

**Describe the solution you'd like**

Please provide, either in the Router object or in the BaseProxyEvent (referenced by the current_event property) access to the ApiGatewayResolver object.  Ideally, the BaseProxyEvent could provide access to both the ApiGatewayResolver object and Router object.

**Describe alternatives you've considered**

Not using the new router functionality.

**Additional context**

**Comment by heitorlessa** [comment]
hey @gwlester  this is now available as part of today's 1.23.0 release :) Thank you again for this feature request!
