### ISSUE TITLE
Feature flags: Support non-boolean values

### ISSUE THREAD

**Issue by ran-isenberg** [awslabs/aws-lambda-powertools-roadmap#71]
Today, the utility feature flags support boolean flags. 
The utility support only boolean values at the moment, hence the wording "flag". 
The utility can support more complex rule match values. I'd like to be able to provide a session context and get back according to the rule engine a more complex object such as Dict, list etc.

**Comment by heitorlessa** [comment]
Hey @ran-isenberg thanks again for the initial implementation! This is available on 1.24 ;) 

https://awslabs.github.io/aws-lambda-powertools-python/latest/utilities/feature_flags/#beyond-boolean-feature-flags
